# environment.yml
name: DL_VCC
channels:
  - conda-forge
dependencies:
  - anndata=0.12.3=pyhd8ed1ab_0
  - array-api-compat=1.12.0=pyhe01879c_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313hc50a443_2
  - crc32c=2.8=py313h9734d34_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - deprecated=1.2.18=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - fonttools=4.60.1=py313h7d74516_0
  - freetype=2.14.1=hce30654_0
  - h5py=3.15.1=nompi_py313h7aa1c8b_100
  - hdf5=1.14.6=nompi_he65715a_103
  - icu=75.1=hfee45f7_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py313hf88c9ab_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.4=h51d1e36_0
  - libblas=3.9.0=37_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcurl=8.16.0=hdece5d2_0
  - libcxx=21.1.4=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=37_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_2
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h7dc4979_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - llvmlite=0.45.1=py313he297ed2_0
  - matplotlib-base=3.10.7=py313h58042b9_0
  - msgpack-python=1.1.2=py313ha61f8ec_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.5=pyhe01879c_0
  - numba=0.62.1=py313h936dde2_0
  - numcodecs=0.16.1=py313h7d16b84_2
  - numpy=2.3.4=py313h9771d21_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h7d16b84_1
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=11.3.0=py313he4c6d0d_3
  - pip=25.2=pyh145f28c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.13.9=hfc2f54d_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h7d74516_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - scanpy=1.11.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py313h6eea1c5_0
  - scipy=1.16.2=py313h0d10b07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - session-info2=0.2.3=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - statsmodels=0.14.5=py313hc577518_1
  - tbb=2022.2.0=h5b2e6d4_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.9.post2=py313h8f79df9_0
  - wrapt=1.17.3=py313hcdf3177_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - zarr=3.1.3=pyhcf101f3_0
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/DL_VCC
